// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.6
// source: api/proto/bgp/provider/v1alpha1/provider.proto

package providerv1alpha1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConfigureSpeakerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Spec          *SpeakerSpec           `protobuf:"bytes,1,opt,name=spec,proto3" json:"spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigureSpeakerRequest) Reset() {
	*x = ConfigureSpeakerRequest{}
	mi := &file_api_proto_bgp_provider_v1alpha1_provider_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigureSpeakerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureSpeakerRequest) ProtoMessage() {}

func (x *ConfigureSpeakerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_bgp_provider_v1alpha1_provider_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureSpeakerRequest.ProtoReflect.Descriptor instead.
func (*ConfigureSpeakerRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_bgp_provider_v1alpha1_provider_proto_rawDescGZIP(), []int{0}
}

func (x *ConfigureSpeakerRequest) GetSpec() *SpeakerSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

type ConfigureSpeakerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Restarted     bool                   `protobuf:"varint,1,opt,name=restarted,proto3" json:"restarted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigureSpeakerResponse) Reset() {
	*x = ConfigureSpeakerResponse{}
	mi := &file_api_proto_bgp_provider_v1alpha1_provider_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigureSpeakerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureSpeakerResponse) ProtoMessage() {}

func (x *ConfigureSpeakerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_bgp_provider_v1alpha1_provider_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureSpeakerResponse.ProtoReflect.Descriptor instead.
func (*ConfigureSpeakerResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_bgp_provider_v1alpha1_provider_proto_rawDescGZIP(), []int{1}
}

func (x *ConfigureSpeakerResponse) GetRestarted() bool {
	if x != nil {
		return x.Restarted
	}
	return false
}

type SpeakerSpec struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AsNumber       int64                  `protobuf:"varint,1,opt,name=as_number,json=asNumber,proto3" json:"as_number,omitempty"`
	RouterId       string                 `protobuf:"bytes,2,opt,name=router_id,json=routerId,proto3" json:"router_id,omitempty"`
	ListenPort     int32                  `protobuf:"varint,3,opt,name=listen_port,json=listenPort,proto3" json:"listen_port,omitempty"`
	Families       []*AddressFamily       `protobuf:"bytes,4,rep,name=families,proto3" json:"families,omitempty"`
	Timers         *TimerConfig           `protobuf:"bytes,5,opt,name=timers,proto3" json:"timers,omitempty"`
	BestPath       *BestPathConfig        `protobuf:"bytes,6,opt,name=best_path,json=bestPath,proto3" json:"best_path,omitempty"`
	RouteReflector *RouteReflectorConfig  `protobuf:"bytes,7,opt,name=route_reflector,json=routeReflector,proto3" json:"route_reflector,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SpeakerSpec) Reset() {
	*x = SpeakerSpec{}
	mi := &file_api_proto_bgp_provider_v1alpha1_provider_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpeakerSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpeakerSpec) ProtoMessage() {}

func (x *SpeakerSpec) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_bgp_provider_v1alpha1_provider_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpeakerSpec.ProtoReflect.Descriptor instead.
func (*SpeakerSpec) Descriptor() ([]byte, []int) {
	return file_api_proto_bgp_provider_v1alpha1_provider_proto_rawDescGZIP(), []int{2}
}

func (x *SpeakerSpec) GetAsNumber() int64 {
	if x != nil {
		return x.AsNumber
	}
	return 0
}

func (x *SpeakerSpec) GetRouterId() string {
	if x != nil {
		return x.RouterId
	}
	return ""
}

func (x *SpeakerSpec) GetListenPort() int32 {
	if x != nil {
		return x.ListenPort
	}
	return 0
}

func (x *SpeakerSpec) GetFamilies() []*AddressFamily {
	if x != nil {
		return x.Families
	}
	return nil
}

func (x *SpeakerSpec) GetTimers() *TimerConfig {
	if x != nil {
		return x.Timers
	}
	return nil
}

func (x *SpeakerSpec) GetBestPath() *BestPathConfig {
	if x != nil {
		return x.BestPath
	}
	return nil
}

func (x *SpeakerSpec) GetRouteReflector() *RouteReflectorConfig {
	if x != nil {
		return x.RouteReflector
	}
	return nil
}

type TimerConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HoldTime      int32                  `protobuf:"varint,1,opt,name=hold_time,json=holdTime,proto3" json:"hold_time,omitempty"`
	Keepalive     int32                  `protobuf:"varint,2,opt,name=keepalive,proto3" json:"keepalive,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimerConfig) Reset() {
	*x = TimerConfig{}
	mi := &file_api_proto_bgp_provider_v1alpha1_provider_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimerConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimerConfig) ProtoMessage() {}

func (x *TimerConfig) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_bgp_provider_v1alpha1_provider_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimerConfig.ProtoReflect.Descriptor instead.
func (*TimerConfig) Descriptor() ([]byte, []int) {
	return file_api_proto_bgp_provider_v1alpha1_provider_proto_rawDescGZIP(), []int{3}
}

func (x *TimerConfig) GetHoldTime() int32 {
	if x != nil {
		return x.HoldTime
	}
	return 0
}

func (x *TimerConfig) GetKeepalive() int32 {
	if x != nil {
		return x.Keepalive
	}
	return 0
}

type BestPathConfig struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AlwaysCompareMed bool                   `protobuf:"varint,1,opt,name=always_compare_med,json=alwaysCompareMed,proto3" json:"always_compare_med,omitempty"`
	DeterministicMed bool                   `protobuf:"varint,2,opt,name=deterministic_med,json=deterministicMed,proto3" json:"deterministic_med,omitempty"`
	CompareRouterId  bool                   `protobuf:"varint,3,opt,name=compare_router_id,json=compareRouterId,proto3" json:"compare_router_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *BestPathConfig) Reset() {
	*x = BestPathConfig{}
	mi := &file_api_proto_bgp_provider_v1alpha1_provider_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BestPathConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BestPathConfig) ProtoMessage() {}

func (x *BestPathConfig) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_bgp_provider_v1alpha1_provider_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BestPathConfig.ProtoReflect.Descriptor instead.
func (*BestPathConfig) Descriptor() ([]byte, []int) {
	return file_api_proto_bgp_provider_v1alpha1_provider_proto_rawDescGZIP(), []int{4}
}

func (x *BestPathConfig) GetAlwaysCompareMed() bool {
	if x != nil {
		return x.AlwaysCompareMed
	}
	return false
}

func (x *BestPathConfig) GetDeterministicMed() bool {
	if x != nil {
		return x.DeterministicMed
	}
	return false
}

func (x *BestPathConfig) GetCompareRouterId() bool {
	if x != nil {
		return x.CompareRouterId
	}
	return false
}

type RouteReflectorConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClusterId     string                 `protobuf:"bytes,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteReflectorConfig) Reset() {
	*x = RouteReflectorConfig{}
	mi := &file_api_proto_bgp_provider_v1alpha1_provider_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteReflectorConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteReflectorConfig) ProtoMessage() {}

func (x *RouteReflectorConfig) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_bgp_provider_v1alpha1_provider_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteReflectorConfig.ProtoReflect.Descriptor instead.
func (*RouteReflectorConfig) Descriptor() ([]byte, []int) {
	return file_api_proto_bgp_provider_v1alpha1_provider_proto_rawDescGZIP(), []int{5}
}

func (x *RouteReflectorConfig) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

type AddOrUpdatePeerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Peer          *PeerSpec              `protobuf:"bytes,1,opt,name=peer,proto3" json:"peer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddOrUpdatePeerRequest) Reset() {
	*x = AddOrUpdatePeerRequest{}
	mi := &file_api_proto_bgp_provider_v1alpha1_provider_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddOrUpdatePeerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddOrUpdatePeerRequest) ProtoMessage() {}

func (x *AddOrUpdatePeerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_bgp_provider_v1alpha1_provider_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddOrUpdatePeerRequest.ProtoReflect.Descriptor instead.
func (*AddOrUpdatePeerRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_bgp_provider_v1alpha1_provider_proto_rawDescGZIP(), []int{6}
}

func (x *AddOrUpdatePeerRequest) GetPeer() *PeerSpec {
	if x != nil {
		return x.Peer
	}
	return nil
}

type AddOrUpdatePeerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddOrUpdatePeerResponse) Reset() {
	*x = AddOrUpdatePeerResponse{}
	mi := &file_api_proto_bgp_provider_v1alpha1_provider_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddOrUpdatePeerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddOrUpdatePeerResponse) ProtoMessage() {}

func (x *AddOrUpdatePeerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_bgp_provider_v1alpha1_provider_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddOrUpdatePeerResponse.ProtoReflect.Descriptor instead.
func (*AddOrUpdatePeerResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_bgp_provider_v1alpha1_provider_proto_rawDescGZIP(), []int{7}
}

type DeletePeerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePeerRequest) Reset() {
	*x = DeletePeerRequest{}
	mi := &file_api_proto_bgp_provider_v1alpha1_provider_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePeerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePeerRequest) ProtoMessage() {}

func (x *DeletePeerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_bgp_provider_v1alpha1_provider_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePeerRequest.ProtoReflect.Descriptor instead.
func (*DeletePeerRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_bgp_provider_v1alpha1_provider_proto_rawDescGZIP(), []int{8}
}

func (x *DeletePeerRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type DeletePeerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePeerResponse) Reset() {
	*x = DeletePeerResponse{}
	mi := &file_api_proto_bgp_provider_v1alpha1_provider_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePeerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePeerResponse) ProtoMessage() {}

func (x *DeletePeerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_bgp_provider_v1alpha1_provider_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePeerResponse.ProtoReflect.Descriptor instead.
func (*DeletePeerResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_bgp_provider_v1alpha1_provider_proto_rawDescGZIP(), []int{9}
}

type PeerSpec struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Address              string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	AsNumber             int64                  `protobuf:"varint,2,opt,name=as_number,json=asNumber,proto3" json:"as_number,omitempty"`
	Families             []*AddressFamily       `protobuf:"bytes,3,rep,name=families,proto3" json:"families,omitempty"`
	Timers               *TimerConfig           `protobuf:"bytes,4,opt,name=timers,proto3" json:"timers,omitempty"`
	AllowAsIn            int32                  `protobuf:"varint,5,opt,name=allow_as_in,json=allowAsIn,proto3" json:"allow_as_in,omitempty"`
	RouteReflectorClient bool                   `protobuf:"varint,6,opt,name=route_reflector_client,json=routeReflectorClient,proto3" json:"route_reflector_client,omitempty"`
	Passive              bool                   `protobuf:"varint,7,opt,name=passive,proto3" json:"passive,omitempty"`
	EbgpMultihop         *int32                 `protobuf:"varint,8,opt,name=ebgp_multihop,json=ebgpMultihop,proto3,oneof" json:"ebgp_multihop,omitempty"`
	TtlSecurity          *int32                 `protobuf:"varint,9,opt,name=ttl_security,json=ttlSecurity,proto3,oneof" json:"ttl_security,omitempty"`
	Password             string                 `protobuf:"bytes,10,opt,name=password,proto3" json:"password,omitempty"`
	RemotePort           int32                  `protobuf:"varint,11,opt,name=remote_port,json=remotePort,proto3" json:"remote_port,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *PeerSpec) Reset() {
	*x = PeerSpec{}
	mi := &file_api_proto_bgp_provider_v1alpha1_provider_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerSpec) ProtoMessage() {}

func (x *PeerSpec) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_bgp_provider_v1alpha1_provider_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerSpec.ProtoReflect.Descriptor instead.
func (*PeerSpec) Descriptor() ([]byte, []int) {
	return file_api_proto_bgp_provider_v1alpha1_provider_proto_rawDescGZIP(), []int{10}
}

func (x *PeerSpec) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *PeerSpec) GetAsNumber() int64 {
	if x != nil {
		return x.AsNumber
	}
	return 0
}

func (x *PeerSpec) GetFamilies() []*AddressFamily {
	if x != nil {
		return x.Families
	}
	return nil
}

func (x *PeerSpec) GetTimers() *TimerConfig {
	if x != nil {
		return x.Timers
	}
	return nil
}

func (x *PeerSpec) GetAllowAsIn() int32 {
	if x != nil {
		return x.AllowAsIn
	}
	return 0
}

func (x *PeerSpec) GetRouteReflectorClient() bool {
	if x != nil {
		return x.RouteReflectorClient
	}
	return false
}

func (x *PeerSpec) GetPassive() bool {
	if x != nil {
		return x.Passive
	}
	return false
}

func (x *PeerSpec) GetEbgpMultihop() int32 {
	if x != nil && x.EbgpMultihop != nil {
		return *x.EbgpMultihop
	}
	return 0
}

func (x *PeerSpec) GetTtlSecurity() int32 {
	if x != nil && x.TtlSecurity != nil {
		return *x.TtlSecurity
	}
	return 0
}

func (x *PeerSpec) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *PeerSpec) GetRemotePort() int32 {
	if x != nil {
		return x.RemotePort
	}
	return 0
}

type AddOrUpdateAdvertisementRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Advertisement *AdvertisementSpec     `protobuf:"bytes,1,opt,name=advertisement,proto3" json:"advertisement,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddOrUpdateAdvertisementRequest) Reset() {
	*x = AddOrUpdateAdvertisementRequest{}
	mi := &file_api_proto_bgp_provider_v1alpha1_provider_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddOrUpdateAdvertisementRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddOrUpdateAdvertisementRequest) ProtoMessage() {}

func (x *AddOrUpdateAdvertisementRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_bgp_provider_v1alpha1_provider_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddOrUpdateAdvertisementRequest.ProtoReflect.Descriptor instead.
func (*AddOrUpdateAdvertisementRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_bgp_provider_v1alpha1_provider_proto_rawDescGZIP(), []int{11}
}

func (x *AddOrUpdateAdvertisementRequest) GetAdvertisement() *AdvertisementSpec {
	if x != nil {
		return x.Advertisement
	}
	return nil
}

type AddOrUpdateAdvertisementResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddOrUpdateAdvertisementResponse) Reset() {
	*x = AddOrUpdateAdvertisementResponse{}
	mi := &file_api_proto_bgp_provider_v1alpha1_provider_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddOrUpdateAdvertisementResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddOrUpdateAdvertisementResponse) ProtoMessage() {}

func (x *AddOrUpdateAdvertisementResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_bgp_provider_v1alpha1_provider_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddOrUpdateAdvertisementResponse.ProtoReflect.Descriptor instead.
func (*AddOrUpdateAdvertisementResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_bgp_provider_v1alpha1_provider_proto_rawDescGZIP(), []int{12}
}

type DeleteAdvertisementRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prefix        string                 `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAdvertisementRequest) Reset() {
	*x = DeleteAdvertisementRequest{}
	mi := &file_api_proto_bgp_provider_v1alpha1_provider_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAdvertisementRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAdvertisementRequest) ProtoMessage() {}

func (x *DeleteAdvertisementRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_bgp_provider_v1alpha1_provider_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAdvertisementRequest.ProtoReflect.Descriptor instead.
func (*DeleteAdvertisementRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_bgp_provider_v1alpha1_provider_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteAdvertisementRequest) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

type DeleteAdvertisementResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAdvertisementResponse) Reset() {
	*x = DeleteAdvertisementResponse{}
	mi := &file_api_proto_bgp_provider_v1alpha1_provider_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAdvertisementResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAdvertisementResponse) ProtoMessage() {}

func (x *DeleteAdvertisementResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_bgp_provider_v1alpha1_provider_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAdvertisementResponse.ProtoReflect.Descriptor instead.
func (*DeleteAdvertisementResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_bgp_provider_v1alpha1_provider_proto_rawDescGZIP(), []int{14}
}

type AdvertisementSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prefixes      []string               `protobuf:"bytes,1,rep,name=prefixes,proto3" json:"prefixes,omitempty"`
	PeerAddresses []string               `protobuf:"bytes,2,rep,name=peer_addresses,json=peerAddresses,proto3" json:"peer_addresses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdvertisementSpec) Reset() {
	*x = AdvertisementSpec{}
	mi := &file_api_proto_bgp_provider_v1alpha1_provider_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdvertisementSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdvertisementSpec) ProtoMessage() {}

func (x *AdvertisementSpec) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_bgp_provider_v1alpha1_provider_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdvertisementSpec.ProtoReflect.Descriptor instead.
func (*AdvertisementSpec) Descriptor() ([]byte, []int) {
	return file_api_proto_bgp_provider_v1alpha1_provider_proto_rawDescGZIP(), []int{15}
}

func (x *AdvertisementSpec) GetPrefixes() []string {
	if x != nil {
		return x.Prefixes
	}
	return nil
}

func (x *AdvertisementSpec) GetPeerAddresses() []string {
	if x != nil {
		return x.PeerAddresses
	}
	return nil
}

type AddOrUpdatePolicyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Policy        *PolicySpec            `protobuf:"bytes,1,opt,name=policy,proto3" json:"policy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddOrUpdatePolicyRequest) Reset() {
	*x = AddOrUpdatePolicyRequest{}
	mi := &file_api_proto_bgp_provider_v1alpha1_provider_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddOrUpdatePolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddOrUpdatePolicyRequest) ProtoMessage() {}

func (x *AddOrUpdatePolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_bgp_provider_v1alpha1_provider_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddOrUpdatePolicyRequest.ProtoReflect.Descriptor instead.
func (*AddOrUpdatePolicyRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_bgp_provider_v1alpha1_provider_proto_rawDescGZIP(), []int{16}
}

func (x *AddOrUpdatePolicyRequest) GetPolicy() *PolicySpec {
	if x != nil {
		return x.Policy
	}
	return nil
}

type AddOrUpdatePolicyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddOrUpdatePolicyResponse) Reset() {
	*x = AddOrUpdatePolicyResponse{}
	mi := &file_api_proto_bgp_provider_v1alpha1_provider_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddOrUpdatePolicyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddOrUpdatePolicyResponse) ProtoMessage() {}

func (x *AddOrUpdatePolicyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_bgp_provider_v1alpha1_provider_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddOrUpdatePolicyResponse.ProtoReflect.Descriptor instead.
func (*AddOrUpdatePolicyResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_bgp_provider_v1alpha1_provider_proto_rawDescGZIP(), []int{17}
}

type DeletePolicyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PolicyName    string                 `protobuf:"bytes,1,opt,name=policy_name,json=policyName,proto3" json:"policy_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePolicyRequest) Reset() {
	*x = DeletePolicyRequest{}
	mi := &file_api_proto_bgp_provider_v1alpha1_provider_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePolicyRequest) ProtoMessage() {}

func (x *DeletePolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_bgp_provider_v1alpha1_provider_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePolicyRequest.ProtoReflect.Descriptor instead.
func (*DeletePolicyRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_bgp_provider_v1alpha1_provider_proto_rawDescGZIP(), []int{18}
}

func (x *DeletePolicyRequest) GetPolicyName() string {
	if x != nil {
		return x.PolicyName
	}
	return ""
}

type DeletePolicyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePolicyResponse) Reset() {
	*x = DeletePolicyResponse{}
	mi := &file_api_proto_bgp_provider_v1alpha1_provider_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePolicyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePolicyResponse) ProtoMessage() {}

func (x *DeletePolicyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_bgp_provider_v1alpha1_provider_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePolicyResponse.ProtoReflect.Descriptor instead.
func (*DeletePolicyResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_bgp_provider_v1alpha1_provider_proto_rawDescGZIP(), []int{19}
}

type PolicySpec struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Name             string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Priority         int32                  `protobuf:"varint,2,opt,name=priority,proto3" json:"priority,omitempty"`
	ImportStatements []*PolicyStatement     `protobuf:"bytes,3,rep,name=import_statements,json=importStatements,proto3" json:"import_statements,omitempty"`
	ExportStatements []*PolicyStatement     `protobuf:"bytes,4,rep,name=export_statements,json=exportStatements,proto3" json:"export_statements,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PolicySpec) Reset() {
	*x = PolicySpec{}
	mi := &file_api_proto_bgp_provider_v1alpha1_provider_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PolicySpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicySpec) ProtoMessage() {}

func (x *PolicySpec) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_bgp_provider_v1alpha1_provider_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicySpec.ProtoReflect.Descriptor instead.
func (*PolicySpec) Descriptor() ([]byte, []int) {
	return file_api_proto_bgp_provider_v1alpha1_provider_proto_rawDescGZIP(), []int{20}
}

func (x *PolicySpec) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PolicySpec) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *PolicySpec) GetImportStatements() []*PolicyStatement {
	if x != nil {
		return x.ImportStatements
	}
	return nil
}

func (x *PolicySpec) GetExportStatements() []*PolicyStatement {
	if x != nil {
		return x.ExportStatements
	}
	return nil
}

type PolicyStatement struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Conditions    *PolicyConditions      `protobuf:"bytes,2,opt,name=conditions,proto3" json:"conditions,omitempty"`
	Actions       *PolicyActions         `protobuf:"bytes,3,opt,name=actions,proto3" json:"actions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PolicyStatement) Reset() {
	*x = PolicyStatement{}
	mi := &file_api_proto_bgp_provider_v1alpha1_provider_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PolicyStatement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicyStatement) ProtoMessage() {}

func (x *PolicyStatement) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_bgp_provider_v1alpha1_provider_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicyStatement.ProtoReflect.Descriptor instead.
func (*PolicyStatement) Descriptor() ([]byte, []int) {
	return file_api_proto_bgp_provider_v1alpha1_provider_proto_rawDescGZIP(), []int{21}
}

func (x *PolicyStatement) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PolicyStatement) GetConditions() *PolicyConditions {
	if x != nil {
		return x.Conditions
	}
	return nil
}

func (x *PolicyStatement) GetActions() *PolicyActions {
	if x != nil {
		return x.Actions
	}
	return nil
}

type PolicyConditions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PrefixSets    []string               `protobuf:"bytes,1,rep,name=prefix_sets,json=prefixSets,proto3" json:"prefix_sets,omitempty"`
	CommunitySet  string                 `protobuf:"bytes,2,opt,name=community_set,json=communitySet,proto3" json:"community_set,omitempty"`
	NextHopSet    string                 `protobuf:"bytes,3,opt,name=next_hop_set,json=nextHopSet,proto3" json:"next_hop_set,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PolicyConditions) Reset() {
	*x = PolicyConditions{}
	mi := &file_api_proto_bgp_provider_v1alpha1_provider_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PolicyConditions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicyConditions) ProtoMessage() {}

func (x *PolicyConditions) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_bgp_provider_v1alpha1_provider_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicyConditions.ProtoReflect.Descriptor instead.
func (*PolicyConditions) Descriptor() ([]byte, []int) {
	return file_api_proto_bgp_provider_v1alpha1_provider_proto_rawDescGZIP(), []int{22}
}

func (x *PolicyConditions) GetPrefixSets() []string {
	if x != nil {
		return x.PrefixSets
	}
	return nil
}

func (x *PolicyConditions) GetCommunitySet() string {
	if x != nil {
		return x.CommunitySet
	}
	return ""
}

func (x *PolicyConditions) GetNextHopSet() string {
	if x != nil {
		return x.NextHopSet
	}
	return ""
}

type PolicyActions struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	RouteDisposition   string                 `protobuf:"bytes,1,opt,name=route_disposition,json=routeDisposition,proto3" json:"route_disposition,omitempty"`
	SetCommunity       *SetCommunityAction    `protobuf:"bytes,2,opt,name=set_community,json=setCommunity,proto3" json:"set_community,omitempty"`
	SetLocalPreference *int32                 `protobuf:"varint,3,opt,name=set_local_preference,json=setLocalPreference,proto3,oneof" json:"set_local_preference,omitempty"`
	SetMed             *int32                 `protobuf:"varint,4,opt,name=set_med,json=setMed,proto3,oneof" json:"set_med,omitempty"`
	SetNextHop         string                 `protobuf:"bytes,5,opt,name=set_next_hop,json=setNextHop,proto3" json:"set_next_hop,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *PolicyActions) Reset() {
	*x = PolicyActions{}
	mi := &file_api_proto_bgp_provider_v1alpha1_provider_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PolicyActions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicyActions) ProtoMessage() {}

func (x *PolicyActions) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_bgp_provider_v1alpha1_provider_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicyActions.ProtoReflect.Descriptor instead.
func (*PolicyActions) Descriptor() ([]byte, []int) {
	return file_api_proto_bgp_provider_v1alpha1_provider_proto_rawDescGZIP(), []int{23}
}

func (x *PolicyActions) GetRouteDisposition() string {
	if x != nil {
		return x.RouteDisposition
	}
	return ""
}

func (x *PolicyActions) GetSetCommunity() *SetCommunityAction {
	if x != nil {
		return x.SetCommunity
	}
	return nil
}

func (x *PolicyActions) GetSetLocalPreference() int32 {
	if x != nil && x.SetLocalPreference != nil {
		return *x.SetLocalPreference
	}
	return 0
}

func (x *PolicyActions) GetSetMed() int32 {
	if x != nil && x.SetMed != nil {
		return *x.SetMed
	}
	return 0
}

func (x *PolicyActions) GetSetNextHop() string {
	if x != nil {
		return x.SetNextHop
	}
	return ""
}

type SetCommunityAction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Communities   []string               `protobuf:"bytes,1,rep,name=communities,proto3" json:"communities,omitempty"`
	Method        string                 `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetCommunityAction) Reset() {
	*x = SetCommunityAction{}
	mi := &file_api_proto_bgp_provider_v1alpha1_provider_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetCommunityAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetCommunityAction) ProtoMessage() {}

func (x *SetCommunityAction) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_bgp_provider_v1alpha1_provider_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetCommunityAction.ProtoReflect.Descriptor instead.
func (*SetCommunityAction) Descriptor() ([]byte, []int) {
	return file_api_proto_bgp_provider_v1alpha1_provider_proto_rawDescGZIP(), []int{24}
}

func (x *SetCommunityAction) GetCommunities() []string {
	if x != nil {
		return x.Communities
	}
	return nil
}

func (x *SetCommunityAction) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

type ReadyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadyRequest) Reset() {
	*x = ReadyRequest{}
	mi := &file_api_proto_bgp_provider_v1alpha1_provider_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadyRequest) ProtoMessage() {}

func (x *ReadyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_bgp_provider_v1alpha1_provider_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadyRequest.ProtoReflect.Descriptor instead.
func (*ReadyRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_bgp_provider_v1alpha1_provider_proto_rawDescGZIP(), []int{25}
}

type ReadyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadyResponse) Reset() {
	*x = ReadyResponse{}
	mi := &file_api_proto_bgp_provider_v1alpha1_provider_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadyResponse) ProtoMessage() {}

func (x *ReadyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_bgp_provider_v1alpha1_provider_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadyResponse.ProtoReflect.Descriptor instead.
func (*ReadyResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_bgp_provider_v1alpha1_provider_proto_rawDescGZIP(), []int{26}
}

type CapabilitiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CapabilitiesRequest) Reset() {
	*x = CapabilitiesRequest{}
	mi := &file_api_proto_bgp_provider_v1alpha1_provider_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapabilitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapabilitiesRequest) ProtoMessage() {}

func (x *CapabilitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_bgp_provider_v1alpha1_provider_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapabilitiesRequest.ProtoReflect.Descriptor instead.
func (*CapabilitiesRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_bgp_provider_v1alpha1_provider_proto_rawDescGZIP(), []int{27}
}

type CapabilitiesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Capabilities  *CapabilitySet         `protobuf:"bytes,1,opt,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CapabilitiesResponse) Reset() {
	*x = CapabilitiesResponse{}
	mi := &file_api_proto_bgp_provider_v1alpha1_provider_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapabilitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapabilitiesResponse) ProtoMessage() {}

func (x *CapabilitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_bgp_provider_v1alpha1_provider_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapabilitiesResponse.ProtoReflect.Descriptor instead.
func (*CapabilitiesResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_bgp_provider_v1alpha1_provider_proto_rawDescGZIP(), []int{28}
}

func (x *CapabilitiesResponse) GetCapabilities() *CapabilitySet {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

type CapabilitySet struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AddressFamilies []*AddressFamily       `protobuf:"bytes,1,rep,name=address_families,json=addressFamilies,proto3" json:"address_families,omitempty"`
	RouteReflection bool                   `protobuf:"varint,2,opt,name=route_reflection,json=routeReflection,proto3" json:"route_reflection,omitempty"`
	Bfd             bool                   `protobuf:"varint,3,opt,name=bfd,proto3" json:"bfd,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CapabilitySet) Reset() {
	*x = CapabilitySet{}
	mi := &file_api_proto_bgp_provider_v1alpha1_provider_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapabilitySet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapabilitySet) ProtoMessage() {}

func (x *CapabilitySet) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_bgp_provider_v1alpha1_provider_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapabilitySet.ProtoReflect.Descriptor instead.
func (*CapabilitySet) Descriptor() ([]byte, []int) {
	return file_api_proto_bgp_provider_v1alpha1_provider_proto_rawDescGZIP(), []int{29}
}

func (x *CapabilitySet) GetAddressFamilies() []*AddressFamily {
	if x != nil {
		return x.AddressFamilies
	}
	return nil
}

func (x *CapabilitySet) GetRouteReflection() bool {
	if x != nil {
		return x.RouteReflection
	}
	return false
}

func (x *CapabilitySet) GetBfd() bool {
	if x != nil {
		return x.Bfd
	}
	return false
}

type AddressFamily struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Afi           string                 `protobuf:"bytes,1,opt,name=afi,proto3" json:"afi,omitempty"`
	Safi          string                 `protobuf:"bytes,2,opt,name=safi,proto3" json:"safi,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddressFamily) Reset() {
	*x = AddressFamily{}
	mi := &file_api_proto_bgp_provider_v1alpha1_provider_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddressFamily) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddressFamily) ProtoMessage() {}

func (x *AddressFamily) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_bgp_provider_v1alpha1_provider_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddressFamily.ProtoReflect.Descriptor instead.
func (*AddressFamily) Descriptor() ([]byte, []int) {
	return file_api_proto_bgp_provider_v1alpha1_provider_proto_rawDescGZIP(), []int{30}
}

func (x *AddressFamily) GetAfi() string {
	if x != nil {
		return x.Afi
	}
	return ""
}

func (x *AddressFamily) GetSafi() string {
	if x != nil {
		return x.Safi
	}
	return ""
}

var File_api_proto_bgp_provider_v1alpha1_provider_proto protoreflect.FileDescriptor

const file_api_proto_bgp_provider_v1alpha1_provider_proto_rawDesc = "" +
	"\n" +
	".api/proto/bgp/provider/v1alpha1/provider.proto\x12\x15bgp.provider.v1alpha1\"Q\n" +
	"\x17ConfigureSpeakerRequest\x126\n" +
	"\x04spec\x18\x01 \x01(\v2\".bgp.provider.v1alpha1.SpeakerSpecR\x04spec\"8\n" +
	"\x18ConfigureSpeakerResponse\x12\x1c\n" +
	"\trestarted\x18\x01 \x01(\bR\trestarted\"\x80\x03\n" +
	"\vSpeakerSpec\x12\x1b\n" +
	"\tas_number\x18\x01 \x01(\x03R\basNumber\x12\x1b\n" +
	"\trouter_id\x18\x02 \x01(\tR\brouterId\x12\x1f\n" +
	"\vlisten_port\x18\x03 \x01(\x05R\n" +
	"listenPort\x12@\n" +
	"\bfamilies\x18\x04 \x03(\v2$.bgp.provider.v1alpha1.AddressFamilyR\bfamilies\x12:\n" +
	"\x06timers\x18\x05 \x01(\v2\".bgp.provider.v1alpha1.TimerConfigR\x06timers\x12B\n" +
	"\tbest_path\x18\x06 \x01(\v2%.bgp.provider.v1alpha1.BestPathConfigR\bbestPath\x12T\n" +
	"\x0froute_reflector\x18\a \x01(\v2+.bgp.provider.v1alpha1.RouteReflectorConfigR\x0erouteReflector\"H\n" +
	"\vTimerConfig\x12\x1b\n" +
	"\thold_time\x18\x01 \x01(\x05R\bholdTime\x12\x1c\n" +
	"\tkeepalive\x18\x02 \x01(\x05R\tkeepalive\"\x97\x01\n" +
	"\x0eBestPathConfig\x12,\n" +
	"\x12always_compare_med\x18\x01 \x01(\bR\x10alwaysCompareMed\x12+\n" +
	"\x11deterministic_med\x18\x02 \x01(\bR\x10deterministicMed\x12*\n" +
	"\x11compare_router_id\x18\x03 \x01(\bR\x0fcompareRouterId\"5\n" +
	"\x14RouteReflectorConfig\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x01 \x01(\tR\tclusterId\"M\n" +
	"\x16AddOrUpdatePeerRequest\x123\n" +
	"\x04peer\x18\x01 \x01(\v2\x1f.bgp.provider.v1alpha1.PeerSpecR\x04peer\"\x19\n" +
	"\x17AddOrUpdatePeerResponse\"-\n" +
	"\x11DeletePeerRequest\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\"\x14\n" +
	"\x12DeletePeerResponse\"\xe1\x03\n" +
	"\bPeerSpec\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x1b\n" +
	"\tas_number\x18\x02 \x01(\x03R\basNumber\x12@\n" +
	"\bfamilies\x18\x03 \x03(\v2$.bgp.provider.v1alpha1.AddressFamilyR\bfamilies\x12:\n" +
	"\x06timers\x18\x04 \x01(\v2\".bgp.provider.v1alpha1.TimerConfigR\x06timers\x12\x1e\n" +
	"\vallow_as_in\x18\x05 \x01(\x05R\tallowAsIn\x124\n" +
	"\x16route_reflector_client\x18\x06 \x01(\bR\x14routeReflectorClient\x12\x18\n" +
	"\apassive\x18\a \x01(\bR\apassive\x12(\n" +
	"\rebgp_multihop\x18\b \x01(\x05H\x00R\febgpMultihop\x88\x01\x01\x12&\n" +
	"\fttl_security\x18\t \x01(\x05H\x01R\vttlSecurity\x88\x01\x01\x12\x1a\n" +
	"\bpassword\x18\n" +
	" \x01(\tR\bpassword\x12\x1f\n" +
	"\vremote_port\x18\v \x01(\x05R\n" +
	"remotePortB\x10\n" +
	"\x0e_ebgp_multihopB\x0f\n" +
	"\r_ttl_security\"q\n" +
	"\x1fAddOrUpdateAdvertisementRequest\x12N\n" +
	"\radvertisement\x18\x01 \x01(\v2(.bgp.provider.v1alpha1.AdvertisementSpecR\radvertisement\"\"\n" +
	" AddOrUpdateAdvertisementResponse\"4\n" +
	"\x1aDeleteAdvertisementRequest\x12\x16\n" +
	"\x06prefix\x18\x01 \x01(\tR\x06prefix\"\x1d\n" +
	"\x1bDeleteAdvertisementResponse\"V\n" +
	"\x11AdvertisementSpec\x12\x1a\n" +
	"\bprefixes\x18\x01 \x03(\tR\bprefixes\x12%\n" +
	"\x0epeer_addresses\x18\x02 \x03(\tR\rpeerAddresses\"U\n" +
	"\x18AddOrUpdatePolicyRequest\x129\n" +
	"\x06policy\x18\x01 \x01(\v2!.bgp.provider.v1alpha1.PolicySpecR\x06policy\"\x1b\n" +
	"\x19AddOrUpdatePolicyResponse\"6\n" +
	"\x13DeletePolicyRequest\x12\x1f\n" +
	"\vpolicy_name\x18\x01 \x01(\tR\n" +
	"policyName\"\x16\n" +
	"\x14DeletePolicyResponse\"\xe6\x01\n" +
	"\n" +
	"PolicySpec\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\bpriority\x18\x02 \x01(\x05R\bpriority\x12S\n" +
	"\x11import_statements\x18\x03 \x03(\v2&.bgp.provider.v1alpha1.PolicyStatementR\x10importStatements\x12S\n" +
	"\x11export_statements\x18\x04 \x03(\v2&.bgp.provider.v1alpha1.PolicyStatementR\x10exportStatements\"\xae\x01\n" +
	"\x0fPolicyStatement\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12G\n" +
	"\n" +
	"conditions\x18\x02 \x01(\v2'.bgp.provider.v1alpha1.PolicyConditionsR\n" +
	"conditions\x12>\n" +
	"\aactions\x18\x03 \x01(\v2$.bgp.provider.v1alpha1.PolicyActionsR\aactions\"z\n" +
	"\x10PolicyConditions\x12\x1f\n" +
	"\vprefix_sets\x18\x01 \x03(\tR\n" +
	"prefixSets\x12#\n" +
	"\rcommunity_set\x18\x02 \x01(\tR\fcommunitySet\x12 \n" +
	"\fnext_hop_set\x18\x03 \x01(\tR\n" +
	"nextHopSet\"\xa8\x02\n" +
	"\rPolicyActions\x12+\n" +
	"\x11route_disposition\x18\x01 \x01(\tR\x10routeDisposition\x12N\n" +
	"\rset_community\x18\x02 \x01(\v2).bgp.provider.v1alpha1.SetCommunityActionR\fsetCommunity\x125\n" +
	"\x14set_local_preference\x18\x03 \x01(\x05H\x00R\x12setLocalPreference\x88\x01\x01\x12\x1c\n" +
	"\aset_med\x18\x04 \x01(\x05H\x01R\x06setMed\x88\x01\x01\x12 \n" +
	"\fset_next_hop\x18\x05 \x01(\tR\n" +
	"setNextHopB\x17\n" +
	"\x15_set_local_preferenceB\n" +
	"\n" +
	"\b_set_med\"N\n" +
	"\x12SetCommunityAction\x12 \n" +
	"\vcommunities\x18\x01 \x03(\tR\vcommunities\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\"\x0e\n" +
	"\fReadyRequest\"\x0f\n" +
	"\rReadyResponse\"\x15\n" +
	"\x13CapabilitiesRequest\"`\n" +
	"\x14CapabilitiesResponse\x12H\n" +
	"\fcapabilities\x18\x01 \x01(\v2$.bgp.provider.v1alpha1.CapabilitySetR\fcapabilities\"\x9d\x01\n" +
	"\rCapabilitySet\x12O\n" +
	"\x10address_families\x18\x01 \x03(\v2$.bgp.provider.v1alpha1.AddressFamilyR\x0faddressFamilies\x12)\n" +
	"\x10route_reflection\x18\x02 \x01(\bR\x0frouteReflection\x12\x10\n" +
	"\x03bfd\x18\x03 \x01(\bR\x03bfd\"5\n" +
	"\rAddressFamily\x12\x10\n" +
	"\x03afi\x18\x01 \x01(\tR\x03afi\x12\x12\n" +
	"\x04safi\x18\x02 \x01(\tR\x04safi2\x88\b\n" +
	"\x12BGPProviderService\x12s\n" +
	"\x10ConfigureSpeaker\x12..bgp.provider.v1alpha1.ConfigureSpeakerRequest\x1a/.bgp.provider.v1alpha1.ConfigureSpeakerResponse\x12p\n" +
	"\x0fAddOrUpdatePeer\x12-.bgp.provider.v1alpha1.AddOrUpdatePeerRequest\x1a..bgp.provider.v1alpha1.AddOrUpdatePeerResponse\x12a\n" +
	"\n" +
	"DeletePeer\x12(.bgp.provider.v1alpha1.DeletePeerRequest\x1a).bgp.provider.v1alpha1.DeletePeerResponse\x12\x8b\x01\n" +
	"\x18AddOrUpdateAdvertisement\x126.bgp.provider.v1alpha1.AddOrUpdateAdvertisementRequest\x1a7.bgp.provider.v1alpha1.AddOrUpdateAdvertisementResponse\x12|\n" +
	"\x13DeleteAdvertisement\x121.bgp.provider.v1alpha1.DeleteAdvertisementRequest\x1a2.bgp.provider.v1alpha1.DeleteAdvertisementResponse\x12v\n" +
	"\x11AddOrUpdatePolicy\x12/.bgp.provider.v1alpha1.AddOrUpdatePolicyRequest\x1a0.bgp.provider.v1alpha1.AddOrUpdatePolicyResponse\x12g\n" +
	"\fDeletePolicy\x12*.bgp.provider.v1alpha1.DeletePolicyRequest\x1a+.bgp.provider.v1alpha1.DeletePolicyResponse\x12R\n" +
	"\x05Ready\x12#.bgp.provider.v1alpha1.ReadyRequest\x1a$.bgp.provider.v1alpha1.ReadyResponse\x12g\n" +
	"\fCapabilities\x12*.bgp.provider.v1alpha1.CapabilitiesRequest\x1a+.bgp.provider.v1alpha1.CapabilitiesResponseBIZGgo.miloapis.com/cosmos/api/proto/bgp/provider/v1alpha1;providerv1alpha1b\x06proto3"

var (
	file_api_proto_bgp_provider_v1alpha1_provider_proto_rawDescOnce sync.Once
	file_api_proto_bgp_provider_v1alpha1_provider_proto_rawDescData []byte
)

func file_api_proto_bgp_provider_v1alpha1_provider_proto_rawDescGZIP() []byte {
	file_api_proto_bgp_provider_v1alpha1_provider_proto_rawDescOnce.Do(func() {
		file_api_proto_bgp_provider_v1alpha1_provider_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_bgp_provider_v1alpha1_provider_proto_rawDesc), len(file_api_proto_bgp_provider_v1alpha1_provider_proto_rawDesc)))
	})
	return file_api_proto_bgp_provider_v1alpha1_provider_proto_rawDescData
}

var file_api_proto_bgp_provider_v1alpha1_provider_proto_msgTypes = make([]protoimpl.MessageInfo, 31)
var file_api_proto_bgp_provider_v1alpha1_provider_proto_goTypes = []any{
	(*ConfigureSpeakerRequest)(nil),          // 0: bgp.provider.v1alpha1.ConfigureSpeakerRequest
	(*ConfigureSpeakerResponse)(nil),         // 1: bgp.provider.v1alpha1.ConfigureSpeakerResponse
	(*SpeakerSpec)(nil),                      // 2: bgp.provider.v1alpha1.SpeakerSpec
	(*TimerConfig)(nil),                      // 3: bgp.provider.v1alpha1.TimerConfig
	(*BestPathConfig)(nil),                   // 4: bgp.provider.v1alpha1.BestPathConfig
	(*RouteReflectorConfig)(nil),             // 5: bgp.provider.v1alpha1.RouteReflectorConfig
	(*AddOrUpdatePeerRequest)(nil),           // 6: bgp.provider.v1alpha1.AddOrUpdatePeerRequest
	(*AddOrUpdatePeerResponse)(nil),          // 7: bgp.provider.v1alpha1.AddOrUpdatePeerResponse
	(*DeletePeerRequest)(nil),                // 8: bgp.provider.v1alpha1.DeletePeerRequest
	(*DeletePeerResponse)(nil),               // 9: bgp.provider.v1alpha1.DeletePeerResponse
	(*PeerSpec)(nil),                         // 10: bgp.provider.v1alpha1.PeerSpec
	(*AddOrUpdateAdvertisementRequest)(nil),  // 11: bgp.provider.v1alpha1.AddOrUpdateAdvertisementRequest
	(*AddOrUpdateAdvertisementResponse)(nil), // 12: bgp.provider.v1alpha1.AddOrUpdateAdvertisementResponse
	(*DeleteAdvertisementRequest)(nil),       // 13: bgp.provider.v1alpha1.DeleteAdvertisementRequest
	(*DeleteAdvertisementResponse)(nil),      // 14: bgp.provider.v1alpha1.DeleteAdvertisementResponse
	(*AdvertisementSpec)(nil),                // 15: bgp.provider.v1alpha1.AdvertisementSpec
	(*AddOrUpdatePolicyRequest)(nil),         // 16: bgp.provider.v1alpha1.AddOrUpdatePolicyRequest
	(*AddOrUpdatePolicyResponse)(nil),        // 17: bgp.provider.v1alpha1.AddOrUpdatePolicyResponse
	(*DeletePolicyRequest)(nil),              // 18: bgp.provider.v1alpha1.DeletePolicyRequest
	(*DeletePolicyResponse)(nil),             // 19: bgp.provider.v1alpha1.DeletePolicyResponse
	(*PolicySpec)(nil),                       // 20: bgp.provider.v1alpha1.PolicySpec
	(*PolicyStatement)(nil),                  // 21: bgp.provider.v1alpha1.PolicyStatement
	(*PolicyConditions)(nil),                 // 22: bgp.provider.v1alpha1.PolicyConditions
	(*PolicyActions)(nil),                    // 23: bgp.provider.v1alpha1.PolicyActions
	(*SetCommunityAction)(nil),               // 24: bgp.provider.v1alpha1.SetCommunityAction
	(*ReadyRequest)(nil),                     // 25: bgp.provider.v1alpha1.ReadyRequest
	(*ReadyResponse)(nil),                    // 26: bgp.provider.v1alpha1.ReadyResponse
	(*CapabilitiesRequest)(nil),              // 27: bgp.provider.v1alpha1.CapabilitiesRequest
	(*CapabilitiesResponse)(nil),             // 28: bgp.provider.v1alpha1.CapabilitiesResponse
	(*CapabilitySet)(nil),                    // 29: bgp.provider.v1alpha1.CapabilitySet
	(*AddressFamily)(nil),                    // 30: bgp.provider.v1alpha1.AddressFamily
}
var file_api_proto_bgp_provider_v1alpha1_provider_proto_depIdxs = []int32{
	2,  // 0: bgp.provider.v1alpha1.ConfigureSpeakerRequest.spec:type_name -> bgp.provider.v1alpha1.SpeakerSpec
	30, // 1: bgp.provider.v1alpha1.SpeakerSpec.families:type_name -> bgp.provider.v1alpha1.AddressFamily
	3,  // 2: bgp.provider.v1alpha1.SpeakerSpec.timers:type_name -> bgp.provider.v1alpha1.TimerConfig
	4,  // 3: bgp.provider.v1alpha1.SpeakerSpec.best_path:type_name -> bgp.provider.v1alpha1.BestPathConfig
	5,  // 4: bgp.provider.v1alpha1.SpeakerSpec.route_reflector:type_name -> bgp.provider.v1alpha1.RouteReflectorConfig
	10, // 5: bgp.provider.v1alpha1.AddOrUpdatePeerRequest.peer:type_name -> bgp.provider.v1alpha1.PeerSpec
	30, // 6: bgp.provider.v1alpha1.PeerSpec.families:type_name -> bgp.provider.v1alpha1.AddressFamily
	3,  // 7: bgp.provider.v1alpha1.PeerSpec.timers:type_name -> bgp.provider.v1alpha1.TimerConfig
	15, // 8: bgp.provider.v1alpha1.AddOrUpdateAdvertisementRequest.advertisement:type_name -> bgp.provider.v1alpha1.AdvertisementSpec
	20, // 9: bgp.provider.v1alpha1.AddOrUpdatePolicyRequest.policy:type_name -> bgp.provider.v1alpha1.PolicySpec
	21, // 10: bgp.provider.v1alpha1.PolicySpec.import_statements:type_name -> bgp.provider.v1alpha1.PolicyStatement
	21, // 11: bgp.provider.v1alpha1.PolicySpec.export_statements:type_name -> bgp.provider.v1alpha1.PolicyStatement
	22, // 12: bgp.provider.v1alpha1.PolicyStatement.conditions:type_name -> bgp.provider.v1alpha1.PolicyConditions
	23, // 13: bgp.provider.v1alpha1.PolicyStatement.actions:type_name -> bgp.provider.v1alpha1.PolicyActions
	24, // 14: bgp.provider.v1alpha1.PolicyActions.set_community:type_name -> bgp.provider.v1alpha1.SetCommunityAction
	29, // 15: bgp.provider.v1alpha1.CapabilitiesResponse.capabilities:type_name -> bgp.provider.v1alpha1.CapabilitySet
	30, // 16: bgp.provider.v1alpha1.CapabilitySet.address_families:type_name -> bgp.provider.v1alpha1.AddressFamily
	0,  // 17: bgp.provider.v1alpha1.BGPProviderService.ConfigureSpeaker:input_type -> bgp.provider.v1alpha1.ConfigureSpeakerRequest
	6,  // 18: bgp.provider.v1alpha1.BGPProviderService.AddOrUpdatePeer:input_type -> bgp.provider.v1alpha1.AddOrUpdatePeerRequest
	8,  // 19: bgp.provider.v1alpha1.BGPProviderService.DeletePeer:input_type -> bgp.provider.v1alpha1.DeletePeerRequest
	11, // 20: bgp.provider.v1alpha1.BGPProviderService.AddOrUpdateAdvertisement:input_type -> bgp.provider.v1alpha1.AddOrUpdateAdvertisementRequest
	13, // 21: bgp.provider.v1alpha1.BGPProviderService.DeleteAdvertisement:input_type -> bgp.provider.v1alpha1.DeleteAdvertisementRequest
	16, // 22: bgp.provider.v1alpha1.BGPProviderService.AddOrUpdatePolicy:input_type -> bgp.provider.v1alpha1.AddOrUpdatePolicyRequest
	18, // 23: bgp.provider.v1alpha1.BGPProviderService.DeletePolicy:input_type -> bgp.provider.v1alpha1.DeletePolicyRequest
	25, // 24: bgp.provider.v1alpha1.BGPProviderService.Ready:input_type -> bgp.provider.v1alpha1.ReadyRequest
	27, // 25: bgp.provider.v1alpha1.BGPProviderService.Capabilities:input_type -> bgp.provider.v1alpha1.CapabilitiesRequest
	1,  // 26: bgp.provider.v1alpha1.BGPProviderService.ConfigureSpeaker:output_type -> bgp.provider.v1alpha1.ConfigureSpeakerResponse
	7,  // 27: bgp.provider.v1alpha1.BGPProviderService.AddOrUpdatePeer:output_type -> bgp.provider.v1alpha1.AddOrUpdatePeerResponse
	9,  // 28: bgp.provider.v1alpha1.BGPProviderService.DeletePeer:output_type -> bgp.provider.v1alpha1.DeletePeerResponse
	12, // 29: bgp.provider.v1alpha1.BGPProviderService.AddOrUpdateAdvertisement:output_type -> bgp.provider.v1alpha1.AddOrUpdateAdvertisementResponse
	14, // 30: bgp.provider.v1alpha1.BGPProviderService.DeleteAdvertisement:output_type -> bgp.provider.v1alpha1.DeleteAdvertisementResponse
	17, // 31: bgp.provider.v1alpha1.BGPProviderService.AddOrUpdatePolicy:output_type -> bgp.provider.v1alpha1.AddOrUpdatePolicyResponse
	19, // 32: bgp.provider.v1alpha1.BGPProviderService.DeletePolicy:output_type -> bgp.provider.v1alpha1.DeletePolicyResponse
	26, // 33: bgp.provider.v1alpha1.BGPProviderService.Ready:output_type -> bgp.provider.v1alpha1.ReadyResponse
	28, // 34: bgp.provider.v1alpha1.BGPProviderService.Capabilities:output_type -> bgp.provider.v1alpha1.CapabilitiesResponse
	26, // [26:35] is the sub-list for method output_type
	17, // [17:26] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_api_proto_bgp_provider_v1alpha1_provider_proto_init() }
func file_api_proto_bgp_provider_v1alpha1_provider_proto_init() {
	if File_api_proto_bgp_provider_v1alpha1_provider_proto != nil {
		return
	}
	file_api_proto_bgp_provider_v1alpha1_provider_proto_msgTypes[10].OneofWrappers = []any{}
	file_api_proto_bgp_provider_v1alpha1_provider_proto_msgTypes[23].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_bgp_provider_v1alpha1_provider_proto_rawDesc), len(file_api_proto_bgp_provider_v1alpha1_provider_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   31,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_bgp_provider_v1alpha1_provider_proto_goTypes,
		DependencyIndexes: file_api_proto_bgp_provider_v1alpha1_provider_proto_depIdxs,
		MessageInfos:      file_api_proto_bgp_provider_v1alpha1_provider_proto_msgTypes,
	}.Build()
	File_api_proto_bgp_provider_v1alpha1_provider_proto = out.File
	file_api_proto_bgp_provider_v1alpha1_provider_proto_goTypes = nil
	file_api_proto_bgp_provider_v1alpha1_provider_proto_depIdxs = nil
}
