// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// source: api/proto/bgp/provider/v1alpha1/provider.proto

package providerv1alpha1

import (
	"context"

	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
)

// BGPProviderServiceClient is the client API for BGPProviderService service.
type BGPProviderServiceClient interface {
	ConfigureSpeaker(ctx context.Context, in *ConfigureSpeakerRequest, opts ...grpc.CallOption) (*ConfigureSpeakerResponse, error)
	AddOrUpdatePeer(ctx context.Context, in *AddOrUpdatePeerRequest, opts ...grpc.CallOption) (*AddOrUpdatePeerResponse, error)
	DeletePeer(ctx context.Context, in *DeletePeerRequest, opts ...grpc.CallOption) (*DeletePeerResponse, error)
	AddOrUpdateAdvertisement(ctx context.Context, in *AddOrUpdateAdvertisementRequest, opts ...grpc.CallOption) (*AddOrUpdateAdvertisementResponse, error)
	DeleteAdvertisement(ctx context.Context, in *DeleteAdvertisementRequest, opts ...grpc.CallOption) (*DeleteAdvertisementResponse, error)
	AddOrUpdatePolicy(ctx context.Context, in *AddOrUpdatePolicyRequest, opts ...grpc.CallOption) (*AddOrUpdatePolicyResponse, error)
	DeletePolicy(ctx context.Context, in *DeletePolicyRequest, opts ...grpc.CallOption) (*DeletePolicyResponse, error)
	Ready(ctx context.Context, in *ReadyRequest, opts ...grpc.CallOption) (*ReadyResponse, error)
	Capabilities(ctx context.Context, in *CapabilitiesRequest, opts ...grpc.CallOption) (*CapabilitiesResponse, error)
}

type bGPProviderServiceClient struct {
	cc grpc.ClientConnInterface
}

// NewBGPProviderServiceClient creates a new BGPProviderServiceClient.
func NewBGPProviderServiceClient(cc grpc.ClientConnInterface) BGPProviderServiceClient {
	return &bGPProviderServiceClient{cc}
}

func (c *bGPProviderServiceClient) ConfigureSpeaker(ctx context.Context, in *ConfigureSpeakerRequest, opts ...grpc.CallOption) (*ConfigureSpeakerResponse, error) {
	out := new(ConfigureSpeakerResponse)
	err := c.cc.Invoke(ctx, "/bgp.provider.v1alpha1.BGPProviderService/ConfigureSpeaker", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bGPProviderServiceClient) AddOrUpdatePeer(ctx context.Context, in *AddOrUpdatePeerRequest, opts ...grpc.CallOption) (*AddOrUpdatePeerResponse, error) {
	out := new(AddOrUpdatePeerResponse)
	err := c.cc.Invoke(ctx, "/bgp.provider.v1alpha1.BGPProviderService/AddOrUpdatePeer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bGPProviderServiceClient) DeletePeer(ctx context.Context, in *DeletePeerRequest, opts ...grpc.CallOption) (*DeletePeerResponse, error) {
	out := new(DeletePeerResponse)
	err := c.cc.Invoke(ctx, "/bgp.provider.v1alpha1.BGPProviderService/DeletePeer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bGPProviderServiceClient) AddOrUpdateAdvertisement(ctx context.Context, in *AddOrUpdateAdvertisementRequest, opts ...grpc.CallOption) (*AddOrUpdateAdvertisementResponse, error) {
	out := new(AddOrUpdateAdvertisementResponse)
	err := c.cc.Invoke(ctx, "/bgp.provider.v1alpha1.BGPProviderService/AddOrUpdateAdvertisement", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bGPProviderServiceClient) DeleteAdvertisement(ctx context.Context, in *DeleteAdvertisementRequest, opts ...grpc.CallOption) (*DeleteAdvertisementResponse, error) {
	out := new(DeleteAdvertisementResponse)
	err := c.cc.Invoke(ctx, "/bgp.provider.v1alpha1.BGPProviderService/DeleteAdvertisement", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bGPProviderServiceClient) AddOrUpdatePolicy(ctx context.Context, in *AddOrUpdatePolicyRequest, opts ...grpc.CallOption) (*AddOrUpdatePolicyResponse, error) {
	out := new(AddOrUpdatePolicyResponse)
	err := c.cc.Invoke(ctx, "/bgp.provider.v1alpha1.BGPProviderService/AddOrUpdatePolicy", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bGPProviderServiceClient) DeletePolicy(ctx context.Context, in *DeletePolicyRequest, opts ...grpc.CallOption) (*DeletePolicyResponse, error) {
	out := new(DeletePolicyResponse)
	err := c.cc.Invoke(ctx, "/bgp.provider.v1alpha1.BGPProviderService/DeletePolicy", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bGPProviderServiceClient) Ready(ctx context.Context, in *ReadyRequest, opts ...grpc.CallOption) (*ReadyResponse, error) {
	out := new(ReadyResponse)
	err := c.cc.Invoke(ctx, "/bgp.provider.v1alpha1.BGPProviderService/Ready", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bGPProviderServiceClient) Capabilities(ctx context.Context, in *CapabilitiesRequest, opts ...grpc.CallOption) (*CapabilitiesResponse, error) {
	out := new(CapabilitiesResponse)
	err := c.cc.Invoke(ctx, "/bgp.provider.v1alpha1.BGPProviderService/Capabilities", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BGPProviderServiceServer is the server API for BGPProviderService service.
type BGPProviderServiceServer interface {
	ConfigureSpeaker(context.Context, *ConfigureSpeakerRequest) (*ConfigureSpeakerResponse, error)
	AddOrUpdatePeer(context.Context, *AddOrUpdatePeerRequest) (*AddOrUpdatePeerResponse, error)
	DeletePeer(context.Context, *DeletePeerRequest) (*DeletePeerResponse, error)
	AddOrUpdateAdvertisement(context.Context, *AddOrUpdateAdvertisementRequest) (*AddOrUpdateAdvertisementResponse, error)
	DeleteAdvertisement(context.Context, *DeleteAdvertisementRequest) (*DeleteAdvertisementResponse, error)
	AddOrUpdatePolicy(context.Context, *AddOrUpdatePolicyRequest) (*AddOrUpdatePolicyResponse, error)
	DeletePolicy(context.Context, *DeletePolicyRequest) (*DeletePolicyResponse, error)
	Ready(context.Context, *ReadyRequest) (*ReadyResponse, error)
	Capabilities(context.Context, *CapabilitiesRequest) (*CapabilitiesResponse, error)
	mustEmbedUnimplementedBGPProviderServiceServer()
}

// UnimplementedBGPProviderServiceServer must be embedded to have forward compatible implementations.
type UnimplementedBGPProviderServiceServer struct{}

func (UnimplementedBGPProviderServiceServer) ConfigureSpeaker(context.Context, *ConfigureSpeakerRequest) (*ConfigureSpeakerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConfigureSpeaker not implemented")
}
func (UnimplementedBGPProviderServiceServer) AddOrUpdatePeer(context.Context, *AddOrUpdatePeerRequest) (*AddOrUpdatePeerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddOrUpdatePeer not implemented")
}
func (UnimplementedBGPProviderServiceServer) DeletePeer(context.Context, *DeletePeerRequest) (*DeletePeerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeletePeer not implemented")
}
func (UnimplementedBGPProviderServiceServer) AddOrUpdateAdvertisement(context.Context, *AddOrUpdateAdvertisementRequest) (*AddOrUpdateAdvertisementResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddOrUpdateAdvertisement not implemented")
}
func (UnimplementedBGPProviderServiceServer) DeleteAdvertisement(context.Context, *DeleteAdvertisementRequest) (*DeleteAdvertisementResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteAdvertisement not implemented")
}
func (UnimplementedBGPProviderServiceServer) AddOrUpdatePolicy(context.Context, *AddOrUpdatePolicyRequest) (*AddOrUpdatePolicyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddOrUpdatePolicy not implemented")
}
func (UnimplementedBGPProviderServiceServer) DeletePolicy(context.Context, *DeletePolicyRequest) (*DeletePolicyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeletePolicy not implemented")
}
func (UnimplementedBGPProviderServiceServer) Ready(context.Context, *ReadyRequest) (*ReadyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ready not implemented")
}
func (UnimplementedBGPProviderServiceServer) Capabilities(context.Context, *CapabilitiesRequest) (*CapabilitiesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Capabilities not implemented")
}
func (UnimplementedBGPProviderServiceServer) mustEmbedUnimplementedBGPProviderServiceServer() {}

// UnsafeBGPProviderServiceServer may be embedded to opt out of forward compatibility for this service.
type UnsafeBGPProviderServiceServer interface {
	mustEmbedUnimplementedBGPProviderServiceServer()
}

// RegisterBGPProviderServiceServer registers the BGPProviderServiceServer with the gRPC server.
func RegisterBGPProviderServiceServer(s grpc.ServiceRegistrar, srv BGPProviderServiceServer) {
	s.RegisterService(&BGPProviderService_ServiceDesc, srv)
}

// BGPProviderService_ServiceDesc is the grpc.ServiceDesc for BGPProviderService service.
var BGPProviderService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bgp.provider.v1alpha1.BGPProviderService",
	HandlerType: (*BGPProviderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{MethodName: "ConfigureSpeaker", Handler: _BGPProviderService_ConfigureSpeaker_Handler},
		{MethodName: "AddOrUpdatePeer", Handler: _BGPProviderService_AddOrUpdatePeer_Handler},
		{MethodName: "DeletePeer", Handler: _BGPProviderService_DeletePeer_Handler},
		{MethodName: "AddOrUpdateAdvertisement", Handler: _BGPProviderService_AddOrUpdateAdvertisement_Handler},
		{MethodName: "DeleteAdvertisement", Handler: _BGPProviderService_DeleteAdvertisement_Handler},
		{MethodName: "AddOrUpdatePolicy", Handler: _BGPProviderService_AddOrUpdatePolicy_Handler},
		{MethodName: "DeletePolicy", Handler: _BGPProviderService_DeletePolicy_Handler},
		{MethodName: "Ready", Handler: _BGPProviderService_Ready_Handler},
		{MethodName: "Capabilities", Handler: _BGPProviderService_Capabilities_Handler},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/bgp/provider/v1alpha1/provider.proto",
}

func _BGPProviderService_ConfigureSpeaker_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigureSpeakerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BGPProviderServiceServer).ConfigureSpeaker(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/bgp.provider.v1alpha1.BGPProviderService/ConfigureSpeaker"}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BGPProviderServiceServer).ConfigureSpeaker(ctx, req.(*ConfigureSpeakerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BGPProviderService_AddOrUpdatePeer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddOrUpdatePeerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BGPProviderServiceServer).AddOrUpdatePeer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/bgp.provider.v1alpha1.BGPProviderService/AddOrUpdatePeer"}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BGPProviderServiceServer).AddOrUpdatePeer(ctx, req.(*AddOrUpdatePeerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BGPProviderService_DeletePeer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePeerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BGPProviderServiceServer).DeletePeer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/bgp.provider.v1alpha1.BGPProviderService/DeletePeer"}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BGPProviderServiceServer).DeletePeer(ctx, req.(*DeletePeerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BGPProviderService_AddOrUpdateAdvertisement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddOrUpdateAdvertisementRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BGPProviderServiceServer).AddOrUpdateAdvertisement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/bgp.provider.v1alpha1.BGPProviderService/AddOrUpdateAdvertisement"}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BGPProviderServiceServer).AddOrUpdateAdvertisement(ctx, req.(*AddOrUpdateAdvertisementRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BGPProviderService_DeleteAdvertisement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAdvertisementRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BGPProviderServiceServer).DeleteAdvertisement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/bgp.provider.v1alpha1.BGPProviderService/DeleteAdvertisement"}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BGPProviderServiceServer).DeleteAdvertisement(ctx, req.(*DeleteAdvertisementRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BGPProviderService_AddOrUpdatePolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddOrUpdatePolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BGPProviderServiceServer).AddOrUpdatePolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/bgp.provider.v1alpha1.BGPProviderService/AddOrUpdatePolicy"}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BGPProviderServiceServer).AddOrUpdatePolicy(ctx, req.(*AddOrUpdatePolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BGPProviderService_DeletePolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BGPProviderServiceServer).DeletePolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/bgp.provider.v1alpha1.BGPProviderService/DeletePolicy"}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BGPProviderServiceServer).DeletePolicy(ctx, req.(*DeletePolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BGPProviderService_Ready_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BGPProviderServiceServer).Ready(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/bgp.provider.v1alpha1.BGPProviderService/Ready"}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BGPProviderServiceServer).Ready(ctx, req.(*ReadyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BGPProviderService_Capabilities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CapabilitiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BGPProviderServiceServer).Capabilities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/bgp.provider.v1alpha1.BGPProviderService/Capabilities"}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BGPProviderServiceServer).Capabilities(ctx, req.(*CapabilitiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}
