// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/proto/bgp/provider/v1alpha1/provider.proto

package providerv1alpha1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConfigureSpeakerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Spec          *SpeakerSpec           `protobuf:"bytes,1,opt,name=spec,proto3" json:"spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigureSpeakerRequest) Reset()         { *x = ConfigureSpeakerRequest{} }
func (x *ConfigureSpeakerRequest) String() string { return protoimpl.X.MessageStringOf(x) }
func (x *ConfigureSpeakerRequest) ProtoMessage()  {}
func (x *ConfigureSpeakerRequest) ProtoReflect() protoreflect.Message {
	return nil // stub
}
func (x *ConfigureSpeakerRequest) GetSpec() *SpeakerSpec { return x.Spec }

type ConfigureSpeakerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Restarted     bool                   `protobuf:"varint,1,opt,name=restarted,proto3" json:"restarted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigureSpeakerResponse) Reset()         { *x = ConfigureSpeakerResponse{} }
func (x *ConfigureSpeakerResponse) String() string { return protoimpl.X.MessageStringOf(x) }
func (x *ConfigureSpeakerResponse) ProtoMessage()  {}
func (x *ConfigureSpeakerResponse) ProtoReflect() protoreflect.Message {
	return nil
}
func (x *ConfigureSpeakerResponse) GetRestarted() bool { return x.Restarted }

type SpeakerSpec struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AsNumber       int64                  `protobuf:"varint,1,opt,name=as_number,json=asNumber,proto3" json:"as_number,omitempty"`
	RouterId       string                 `protobuf:"bytes,2,opt,name=router_id,json=routerId,proto3" json:"router_id,omitempty"`
	ListenPort     int32                  `protobuf:"varint,3,opt,name=listen_port,json=listenPort,proto3" json:"listen_port,omitempty"`
	Families       []*AddressFamily       `protobuf:"bytes,4,rep,name=families,proto3" json:"families,omitempty"`
	Timers         *TimerConfig           `protobuf:"bytes,5,opt,name=timers,proto3" json:"timers,omitempty"`
	BestPath       *BestPathConfig        `protobuf:"bytes,6,opt,name=best_path,json=bestPath,proto3" json:"best_path,omitempty"`
	RouteReflector *RouteReflectorConfig  `protobuf:"bytes,7,opt,name=route_reflector,json=routeReflector,proto3" json:"route_reflector,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SpeakerSpec) Reset()                                   { *x = SpeakerSpec{} }
func (x *SpeakerSpec) String() string                           { return protoimpl.X.MessageStringOf(x) }
func (x *SpeakerSpec) ProtoMessage()                            {}
func (x *SpeakerSpec) ProtoReflect() protoreflect.Message       { return nil }
func (x *SpeakerSpec) GetAsNumber() int64                       { return x.AsNumber }
func (x *SpeakerSpec) GetRouterId() string                      { return x.RouterId }
func (x *SpeakerSpec) GetListenPort() int32                     { return x.ListenPort }
func (x *SpeakerSpec) GetFamilies() []*AddressFamily            { return x.Families }
func (x *SpeakerSpec) GetTimers() *TimerConfig                  { return x.Timers }
func (x *SpeakerSpec) GetBestPath() *BestPathConfig             { return x.BestPath }
func (x *SpeakerSpec) GetRouteReflector() *RouteReflectorConfig { return x.RouteReflector }

type TimerConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HoldTime      int32                  `protobuf:"varint,1,opt,name=hold_time,json=holdTime,proto3" json:"hold_time,omitempty"`
	Keepalive     int32                  `protobuf:"varint,2,opt,name=keepalive,proto3" json:"keepalive,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimerConfig) Reset()                             { *x = TimerConfig{} }
func (x *TimerConfig) String() string                     { return protoimpl.X.MessageStringOf(x) }
func (x *TimerConfig) ProtoMessage()                      {}
func (x *TimerConfig) ProtoReflect() protoreflect.Message { return nil }
func (x *TimerConfig) GetHoldTime() int32                 { return x.HoldTime }
func (x *TimerConfig) GetKeepalive() int32                { return x.Keepalive }

type BestPathConfig struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AlwaysCompareMed bool                   `protobuf:"varint,1,opt,name=always_compare_med,json=alwaysCompareMed,proto3" json:"always_compare_med,omitempty"`
	DeterministicMed bool                   `protobuf:"varint,2,opt,name=deterministic_med,json=deterministicMed,proto3" json:"deterministic_med,omitempty"`
	CompareRouterId  bool                   `protobuf:"varint,3,opt,name=compare_router_id,json=compareRouterId,proto3" json:"compare_router_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *BestPathConfig) Reset()                             { *x = BestPathConfig{} }
func (x *BestPathConfig) String() string                     { return protoimpl.X.MessageStringOf(x) }
func (x *BestPathConfig) ProtoMessage()                      {}
func (x *BestPathConfig) ProtoReflect() protoreflect.Message { return nil }
func (x *BestPathConfig) GetAlwaysCompareMed() bool          { return x.AlwaysCompareMed }
func (x *BestPathConfig) GetDeterministicMed() bool          { return x.DeterministicMed }
func (x *BestPathConfig) GetCompareRouterId() bool           { return x.CompareRouterId }

type RouteReflectorConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClusterId     string                 `protobuf:"bytes,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteReflectorConfig) Reset()                             { *x = RouteReflectorConfig{} }
func (x *RouteReflectorConfig) String() string                     { return protoimpl.X.MessageStringOf(x) }
func (x *RouteReflectorConfig) ProtoMessage()                      {}
func (x *RouteReflectorConfig) ProtoReflect() protoreflect.Message { return nil }
func (x *RouteReflectorConfig) GetClusterId() string               { return x.ClusterId }

type AddOrUpdatePeerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Peer          *PeerSpec              `protobuf:"bytes,1,opt,name=peer,proto3" json:"peer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddOrUpdatePeerRequest) Reset()                             { *x = AddOrUpdatePeerRequest{} }
func (x *AddOrUpdatePeerRequest) String() string                     { return protoimpl.X.MessageStringOf(x) }
func (x *AddOrUpdatePeerRequest) ProtoMessage()                      {}
func (x *AddOrUpdatePeerRequest) ProtoReflect() protoreflect.Message { return nil }
func (x *AddOrUpdatePeerRequest) GetPeer() *PeerSpec                 { return x.Peer }

type AddOrUpdatePeerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddOrUpdatePeerResponse) Reset()                             { *x = AddOrUpdatePeerResponse{} }
func (x *AddOrUpdatePeerResponse) String() string                     { return protoimpl.X.MessageStringOf(x) }
func (x *AddOrUpdatePeerResponse) ProtoMessage()                      {}
func (x *AddOrUpdatePeerResponse) ProtoReflect() protoreflect.Message { return nil }

type DeletePeerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePeerRequest) Reset()                             { *x = DeletePeerRequest{} }
func (x *DeletePeerRequest) String() string                     { return protoimpl.X.MessageStringOf(x) }
func (x *DeletePeerRequest) ProtoMessage()                      {}
func (x *DeletePeerRequest) ProtoReflect() protoreflect.Message { return nil }
func (x *DeletePeerRequest) GetAddress() string                 { return x.Address }

type DeletePeerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePeerResponse) Reset()                             { *x = DeletePeerResponse{} }
func (x *DeletePeerResponse) String() string                     { return protoimpl.X.MessageStringOf(x) }
func (x *DeletePeerResponse) ProtoMessage()                      {}
func (x *DeletePeerResponse) ProtoReflect() protoreflect.Message { return nil }

type PeerSpec struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Address              string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	AsNumber             int64                  `protobuf:"varint,2,opt,name=as_number,json=asNumber,proto3" json:"as_number,omitempty"`
	Families             []*AddressFamily       `protobuf:"bytes,3,rep,name=families,proto3" json:"families,omitempty"`
	Timers               *TimerConfig           `protobuf:"bytes,4,opt,name=timers,proto3" json:"timers,omitempty"`
	AllowAsIn            int32                  `protobuf:"varint,5,opt,name=allow_as_in,json=allowAsIn,proto3" json:"allow_as_in,omitempty"`
	RouteReflectorClient bool                   `protobuf:"varint,6,opt,name=route_reflector_client,json=routeReflectorClient,proto3" json:"route_reflector_client,omitempty"`
	Passive              bool                   `protobuf:"varint,7,opt,name=passive,proto3" json:"passive,omitempty"`
	EbgpMultihop         *int32                 `protobuf:"varint,8,opt,name=ebgp_multihop,json=ebgpMultihop,proto3,oneof" json:"ebgp_multihop,omitempty"`
	TtlSecurity          *int32                 `protobuf:"varint,9,opt,name=ttl_security,json=ttlSecurity,proto3,oneof" json:"ttl_security,omitempty"`
	Password             string                 `protobuf:"bytes,10,opt,name=password,proto3" json:"password,omitempty"`
	RemotePort           int32                  `protobuf:"varint,11,opt,name=remote_port,json=remotePort,proto3" json:"remote_port,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *PeerSpec) Reset()                             { *x = PeerSpec{} }
func (x *PeerSpec) String() string                     { return protoimpl.X.MessageStringOf(x) }
func (x *PeerSpec) ProtoMessage()                      {}
func (x *PeerSpec) ProtoReflect() protoreflect.Message { return nil }
func (x *PeerSpec) GetAddress() string                 { return x.Address }
func (x *PeerSpec) GetAsNumber() int64                 { return x.AsNumber }
func (x *PeerSpec) GetFamilies() []*AddressFamily      { return x.Families }
func (x *PeerSpec) GetTimers() *TimerConfig            { return x.Timers }
func (x *PeerSpec) GetAllowAsIn() int32                { return x.AllowAsIn }
func (x *PeerSpec) GetRouteReflectorClient() bool      { return x.RouteReflectorClient }
func (x *PeerSpec) GetPassive() bool                   { return x.Passive }
func (x *PeerSpec) GetEbgpMultihop() int32 {
	if x.EbgpMultihop != nil {
		return *x.EbgpMultihop
	}
	return 0
}
func (x *PeerSpec) GetTtlSecurity() int32 {
	if x.TtlSecurity != nil {
		return *x.TtlSecurity
	}
	return 0
}
func (x *PeerSpec) GetPassword() string  { return x.Password }
func (x *PeerSpec) GetRemotePort() int32 { return x.RemotePort }

type AddOrUpdateAdvertisementRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Advertisement *AdvertisementSpec     `protobuf:"bytes,1,opt,name=advertisement,proto3" json:"advertisement,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddOrUpdateAdvertisementRequest) Reset()                             { *x = AddOrUpdateAdvertisementRequest{} }
func (x *AddOrUpdateAdvertisementRequest) String() string                     { return protoimpl.X.MessageStringOf(x) }
func (x *AddOrUpdateAdvertisementRequest) ProtoMessage()                      {}
func (x *AddOrUpdateAdvertisementRequest) ProtoReflect() protoreflect.Message { return nil }
func (x *AddOrUpdateAdvertisementRequest) GetAdvertisement() *AdvertisementSpec {
	return x.Advertisement
}

type AddOrUpdateAdvertisementResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddOrUpdateAdvertisementResponse) Reset()                             { *x = AddOrUpdateAdvertisementResponse{} }
func (x *AddOrUpdateAdvertisementResponse) String() string                     { return protoimpl.X.MessageStringOf(x) }
func (x *AddOrUpdateAdvertisementResponse) ProtoMessage()                      {}
func (x *AddOrUpdateAdvertisementResponse) ProtoReflect() protoreflect.Message { return nil }

type DeleteAdvertisementRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prefix        string                 `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAdvertisementRequest) Reset()                             { *x = DeleteAdvertisementRequest{} }
func (x *DeleteAdvertisementRequest) String() string                     { return protoimpl.X.MessageStringOf(x) }
func (x *DeleteAdvertisementRequest) ProtoMessage()                      {}
func (x *DeleteAdvertisementRequest) ProtoReflect() protoreflect.Message { return nil }
func (x *DeleteAdvertisementRequest) GetPrefix() string                  { return x.Prefix }

type DeleteAdvertisementResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAdvertisementResponse) Reset()                             { *x = DeleteAdvertisementResponse{} }
func (x *DeleteAdvertisementResponse) String() string                     { return protoimpl.X.MessageStringOf(x) }
func (x *DeleteAdvertisementResponse) ProtoMessage()                      {}
func (x *DeleteAdvertisementResponse) ProtoReflect() protoreflect.Message { return nil }

type AdvertisementSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prefixes      []string               `protobuf:"bytes,1,rep,name=prefixes,proto3" json:"prefixes,omitempty"`
	PeerAddresses []string               `protobuf:"bytes,2,rep,name=peer_addresses,json=peerAddresses,proto3" json:"peer_addresses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdvertisementSpec) Reset()                             { *x = AdvertisementSpec{} }
func (x *AdvertisementSpec) String() string                     { return protoimpl.X.MessageStringOf(x) }
func (x *AdvertisementSpec) ProtoMessage()                      {}
func (x *AdvertisementSpec) ProtoReflect() protoreflect.Message { return nil }
func (x *AdvertisementSpec) GetPrefixes() []string              { return x.Prefixes }
func (x *AdvertisementSpec) GetPeerAddresses() []string         { return x.PeerAddresses }

type AddOrUpdatePolicyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Policy        *PolicySpec            `protobuf:"bytes,1,opt,name=policy,proto3" json:"policy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddOrUpdatePolicyRequest) Reset()                             { *x = AddOrUpdatePolicyRequest{} }
func (x *AddOrUpdatePolicyRequest) String() string                     { return protoimpl.X.MessageStringOf(x) }
func (x *AddOrUpdatePolicyRequest) ProtoMessage()                      {}
func (x *AddOrUpdatePolicyRequest) ProtoReflect() protoreflect.Message { return nil }
func (x *AddOrUpdatePolicyRequest) GetPolicy() *PolicySpec             { return x.Policy }

type AddOrUpdatePolicyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddOrUpdatePolicyResponse) Reset()                             { *x = AddOrUpdatePolicyResponse{} }
func (x *AddOrUpdatePolicyResponse) String() string                     { return protoimpl.X.MessageStringOf(x) }
func (x *AddOrUpdatePolicyResponse) ProtoMessage()                      {}
func (x *AddOrUpdatePolicyResponse) ProtoReflect() protoreflect.Message { return nil }

type DeletePolicyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PolicyName    string                 `protobuf:"bytes,1,opt,name=policy_name,json=policyName,proto3" json:"policy_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePolicyRequest) Reset()                             { *x = DeletePolicyRequest{} }
func (x *DeletePolicyRequest) String() string                     { return protoimpl.X.MessageStringOf(x) }
func (x *DeletePolicyRequest) ProtoMessage()                      {}
func (x *DeletePolicyRequest) ProtoReflect() protoreflect.Message { return nil }
func (x *DeletePolicyRequest) GetPolicyName() string              { return x.PolicyName }

type DeletePolicyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePolicyResponse) Reset()                             { *x = DeletePolicyResponse{} }
func (x *DeletePolicyResponse) String() string                     { return protoimpl.X.MessageStringOf(x) }
func (x *DeletePolicyResponse) ProtoMessage()                      {}
func (x *DeletePolicyResponse) ProtoReflect() protoreflect.Message { return nil }

type PolicySpec struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Name             string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Priority         int32                  `protobuf:"varint,2,opt,name=priority,proto3" json:"priority,omitempty"`
	ImportStatements []*PolicyStatement     `protobuf:"bytes,3,rep,name=import_statements,json=importStatements,proto3" json:"import_statements,omitempty"`
	ExportStatements []*PolicyStatement     `protobuf:"bytes,4,rep,name=export_statements,json=exportStatements,proto3" json:"export_statements,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PolicySpec) Reset()                                  { *x = PolicySpec{} }
func (x *PolicySpec) String() string                          { return protoimpl.X.MessageStringOf(x) }
func (x *PolicySpec) ProtoMessage()                           {}
func (x *PolicySpec) ProtoReflect() protoreflect.Message      { return nil }
func (x *PolicySpec) GetName() string                         { return x.Name }
func (x *PolicySpec) GetPriority() int32                      { return x.Priority }
func (x *PolicySpec) GetImportStatements() []*PolicyStatement { return x.ImportStatements }
func (x *PolicySpec) GetExportStatements() []*PolicyStatement { return x.ExportStatements }

type PolicyStatement struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Conditions    *PolicyConditions      `protobuf:"bytes,2,opt,name=conditions,proto3" json:"conditions,omitempty"`
	Actions       *PolicyActions         `protobuf:"bytes,3,opt,name=actions,proto3" json:"actions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PolicyStatement) Reset()                             { *x = PolicyStatement{} }
func (x *PolicyStatement) String() string                     { return protoimpl.X.MessageStringOf(x) }
func (x *PolicyStatement) ProtoMessage()                      {}
func (x *PolicyStatement) ProtoReflect() protoreflect.Message { return nil }
func (x *PolicyStatement) GetName() string                    { return x.Name }
func (x *PolicyStatement) GetConditions() *PolicyConditions   { return x.Conditions }
func (x *PolicyStatement) GetActions() *PolicyActions         { return x.Actions }

type PolicyConditions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PrefixSets    []string               `protobuf:"bytes,1,rep,name=prefix_sets,json=prefixSets,proto3" json:"prefix_sets,omitempty"`
	CommunitySet  string                 `protobuf:"bytes,2,opt,name=community_set,json=communitySet,proto3" json:"community_set,omitempty"`
	NextHopSet    string                 `protobuf:"bytes,3,opt,name=next_hop_set,json=nextHopSet,proto3" json:"next_hop_set,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PolicyConditions) Reset()                             { *x = PolicyConditions{} }
func (x *PolicyConditions) String() string                     { return protoimpl.X.MessageStringOf(x) }
func (x *PolicyConditions) ProtoMessage()                      {}
func (x *PolicyConditions) ProtoReflect() protoreflect.Message { return nil }
func (x *PolicyConditions) GetPrefixSets() []string            { return x.PrefixSets }
func (x *PolicyConditions) GetCommunitySet() string            { return x.CommunitySet }
func (x *PolicyConditions) GetNextHopSet() string              { return x.NextHopSet }

type PolicyActions struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	RouteDisposition   string                 `protobuf:"bytes,1,opt,name=route_disposition,json=routeDisposition,proto3" json:"route_disposition,omitempty"`
	SetCommunity       *SetCommunityAction    `protobuf:"bytes,2,opt,name=set_community,json=setCommunity,proto3" json:"set_community,omitempty"`
	SetLocalPreference *int32                 `protobuf:"varint,3,opt,name=set_local_preference,json=setLocalPreference,proto3,oneof" json:"set_local_preference,omitempty"`
	SetMed             *int32                 `protobuf:"varint,4,opt,name=set_med,json=setMed,proto3,oneof" json:"set_med,omitempty"`
	SetNextHop         string                 `protobuf:"bytes,5,opt,name=set_next_hop,json=setNextHop,proto3" json:"set_next_hop,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *PolicyActions) Reset()                               { *x = PolicyActions{} }
func (x *PolicyActions) String() string                       { return protoimpl.X.MessageStringOf(x) }
func (x *PolicyActions) ProtoMessage()                        {}
func (x *PolicyActions) ProtoReflect() protoreflect.Message   { return nil }
func (x *PolicyActions) GetRouteDisposition() string          { return x.RouteDisposition }
func (x *PolicyActions) GetSetCommunity() *SetCommunityAction { return x.SetCommunity }
func (x *PolicyActions) GetSetLocalPreference() int32 {
	if x.SetLocalPreference != nil {
		return *x.SetLocalPreference
	}
	return 0
}
func (x *PolicyActions) GetSetMed() int32 {
	if x.SetMed != nil {
		return *x.SetMed
	}
	return 0
}
func (x *PolicyActions) GetSetNextHop() string { return x.SetNextHop }

type SetCommunityAction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Communities   []string               `protobuf:"bytes,1,rep,name=communities,proto3" json:"communities,omitempty"`
	Method        string                 `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetCommunityAction) Reset()                             { *x = SetCommunityAction{} }
func (x *SetCommunityAction) String() string                     { return protoimpl.X.MessageStringOf(x) }
func (x *SetCommunityAction) ProtoMessage()                      {}
func (x *SetCommunityAction) ProtoReflect() protoreflect.Message { return nil }
func (x *SetCommunityAction) GetCommunities() []string           { return x.Communities }
func (x *SetCommunityAction) GetMethod() string                  { return x.Method }

type ReadyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadyRequest) Reset()                             { *x = ReadyRequest{} }
func (x *ReadyRequest) String() string                     { return protoimpl.X.MessageStringOf(x) }
func (x *ReadyRequest) ProtoMessage()                      {}
func (x *ReadyRequest) ProtoReflect() protoreflect.Message { return nil }

type ReadyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadyResponse) Reset()                             { *x = ReadyResponse{} }
func (x *ReadyResponse) String() string                     { return protoimpl.X.MessageStringOf(x) }
func (x *ReadyResponse) ProtoMessage()                      {}
func (x *ReadyResponse) ProtoReflect() protoreflect.Message { return nil }

type CapabilitiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CapabilitiesRequest) Reset()                             { *x = CapabilitiesRequest{} }
func (x *CapabilitiesRequest) String() string                     { return protoimpl.X.MessageStringOf(x) }
func (x *CapabilitiesRequest) ProtoMessage()                      {}
func (x *CapabilitiesRequest) ProtoReflect() protoreflect.Message { return nil }

type CapabilitiesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Capabilities  *CapabilitySet         `protobuf:"bytes,1,opt,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CapabilitiesResponse) Reset()                             { *x = CapabilitiesResponse{} }
func (x *CapabilitiesResponse) String() string                     { return protoimpl.X.MessageStringOf(x) }
func (x *CapabilitiesResponse) ProtoMessage()                      {}
func (x *CapabilitiesResponse) ProtoReflect() protoreflect.Message { return nil }
func (x *CapabilitiesResponse) GetCapabilities() *CapabilitySet    { return x.Capabilities }

type CapabilitySet struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AddressFamilies []*AddressFamily       `protobuf:"bytes,1,rep,name=address_families,json=addressFamilies,proto3" json:"address_families,omitempty"`
	RouteReflection bool                   `protobuf:"varint,2,opt,name=route_reflection,json=routeReflection,proto3" json:"route_reflection,omitempty"`
	Bfd             bool                   `protobuf:"varint,3,opt,name=bfd,proto3" json:"bfd,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CapabilitySet) Reset()                               { *x = CapabilitySet{} }
func (x *CapabilitySet) String() string                       { return protoimpl.X.MessageStringOf(x) }
func (x *CapabilitySet) ProtoMessage()                        {}
func (x *CapabilitySet) ProtoReflect() protoreflect.Message   { return nil }
func (x *CapabilitySet) GetAddressFamilies() []*AddressFamily { return x.AddressFamilies }
func (x *CapabilitySet) GetRouteReflection() bool             { return x.RouteReflection }
func (x *CapabilitySet) GetBfd() bool                         { return x.Bfd }

type AddressFamily struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Afi           string                 `protobuf:"bytes,1,opt,name=afi,proto3" json:"afi,omitempty"`
	Safi          string                 `protobuf:"bytes,2,opt,name=safi,proto3" json:"safi,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddressFamily) Reset()                             { *x = AddressFamily{} }
func (x *AddressFamily) String() string                     { return protoimpl.X.MessageStringOf(x) }
func (x *AddressFamily) ProtoMessage()                      {}
func (x *AddressFamily) ProtoReflect() protoreflect.Message { return nil }
func (x *AddressFamily) GetAfi() string                     { return x.Afi }
func (x *AddressFamily) GetSafi() string                    { return x.Safi }

// Ensure unused imports are referenced.
var (
	_ sync.Mutex
	_ = reflect.TypeOf
	_ = unsafe.Sizeof(0)
)
