apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - bgp.miloapis.com_bgpconfigurations.yaml
  - bgp.miloapis.com_bgpendpoints.yaml
  - bgp.miloapis.com_bgpsessions.yaml
  - bgp.miloapis.com_bgppeeringpolicies.yaml
  - bgp.miloapis.com_bgpadvertisements.yaml
  - bgp.miloapis.com_bgproutepolicies.yaml
