apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - bgp.miloapis.com_bgprouters.yaml
  - bgp.miloapis.com_bgppeers.yaml
  - bgp.miloapis.com_bgpadvertisements.yaml
  - bgp.miloapis.com_bgppolicies.yaml
  - bgp.miloapis.com_bgpvrfinstances.yaml
  - vpc.miloapis.com_vpcs.yaml
  - vpc.miloapis.com_vpcattachments.yaml
