apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - providers.bgp.miloapis.com_bgpproviders.yaml
  - bgp.miloapis.com_bgpinstances.yaml
  - bgp.miloapis.com_bgppeers.yaml
  - bgp.miloapis.com_bgpadvertisements.yaml
  - bgp.miloapis.com_bgproutepolicies.yaml
  - bgp.miloapis.com_bgpsessions.yaml
  - bgp.miloapis.com_bgpexternalpeers.yaml
  - bgp.miloapis.com_bgpvrfinstances.yaml
  - vpc.miloapis.com_vpcs.yaml
  - vpc.miloapis.com_vpcattachments.yaml
